

S5 KTU SYSTEM SOFTWARE LAB
__________________________________

1 -> FCFS ,SJF,PRIORITY, RR
2 -> SINGLE ,TWO LEVEL , HIERARCHIAL DIRECTORY STRUCTURE
3 -> BANKERS ALGORITHM
4 -> DISK SCHEDULING ALGORITHMS (FCFS ,SCAN ,CSCAN)
5 -> PRODUCER CONSUMER PROBLEM JAVA
6 -> DINING PHILOSOPHER JAVA
7 -> SYMBOL TABLE USING HASHING
8 -> PASS 1 OF SINGLE PASS ASSEMBLER
9 -> PASS 2 OF SINGLE PASS ASSEMBLER
10 -> SINGLE PASS ASSEMBLER
11 -> ABSOLUTE 
12 -> RELOCATION LOADER
13  -> XV6 ASSIGNMENT




